dataset:
  path: "../../input/optiver-realized-volatility-prediction"
  train: "fea0_train_best.pkl"
  test: "fea0_test_best.pkl"

model:
  verbose: 100
  fold: 10
  fold_name: "group"

params:
  bagging_fraction: 0.8339152856093507
  bagging_freq: 81
  bagging_seed: 42
  boosting: gbdt
  drop_seed: 42
  feature_fraction: 0.2788441133807552
  feature_fraction_bynode: 0.10496990541124217
  feature_fraction_seed: 42
  lambda_l1: 8.219772826786357
  lambda_l2: 1.6709557931179373
  learning_rate: 0.02904392076997777
  max_depth: 9
  min_data_in_leaf: 885
  min_sum_hessian_in_leaf: 43.16734307889972
  n_jobs: -1
  num_leaves: 1018
  objective: rmse
  seed: 42
  verbosity: -1
