dataset:
  path: "../../input/optiver-realized-volatility-prediction/"
  train: "train.pkl"
  test: "test.pkl"

optimization:
  trials: 100
  params: best_lgbm_params.yaml
model:
  fold: 5
  fold_name: "group"